### ISSUE TITLE
Trying to follow example

### ISSUE THREAD

**Issue by mhdawson** [sigstore/sigstore-js#17]
**Description**

I was following the steps in the README.md but when I try to sign I just get:

```
[midawson@midawson sigstore-js]$ ./bin/sigstore.js sign ./node-addon-api-4.3.0.tgz >signature
Error: No identity token provided
    at Signer.getIdentityToken (/home/midawson/sigstore/sigstore-js/dist/sign.js:59:15)
    at async Signer.sign (/home/midawson/sigstore/sigstore-js/dist/sign.js:21:31)
    at async sign (/home/midawson/sigstore/sigstore-js/dist/cli/index.js:48:23)
    at async cli (/home/midawson/sigstore/sigstore-js/dist/cli/index.js:27:13)
    at async Object.processArgv (/home/midawson/sigstore/sigstore-js/dist/cli/index.js:79:9)
```

I'm running on RHEL 8.  Is there some additional configurationt that I need to get the brower window to pop up ?

**Version**

built from main on  Aug 3 2022

**Comment by bdehamer** [comment]
We've got a PR open right now which should address the cross-platform browser opening issue. Look for this to land soon.

https://github.com/sigstore/sigstore-js/pull/16

**Comment by mhdawson** [comment]
@bdehamer thanks will keep a look out for that to land.
